### ISSUE TITLE
bs-dev should use File.pathSeparator instead of ";"

### ISSUE THREAD

**Issue by Jab125** [MinecraftForge/Bootstrap#6]
Here in `BootstrapDevClasspathFixer`:
https://github.com/MinecraftForge/Bootstrap/blob/394896eab996476c9162f4e4f4c035b837fefa40/bs-dev/src/main/java/net/minecraftforge/bootstrap/dev/BootstrapDevClasspathFixer.java#L70 `;` should just be replaced with `File.pathSeparator`:
```diff
- for (var entry : mod_classes.split(";")) { 
+ for (var entry : mod_classes.split(File.pathSeparator)) { 
```

**Comment by LexManos** [comment]
I even write that in the doc on the method, whoops, thanks for taking a look. It is still the recommended method that you simply merge your sourcesets so that the whole union system is not needed. But thanks This will fix it for cases that don't want to do that.
